export enum PersonType {
    NASI_A_USPESNI = 'NASI_A_USPESNI',
    NOSIOCI_VUKOVE_DIPLOME = 'NOSIOCI_VUKOVE_DIPLOME',
    ZAPOSLENI = 'ZAPOSLENI',
    SKOLSKI_ODBOR = 'SKOLSKI_ODBOR',
    SAVET_RODITELJA = 'SAVET_RODITELJA'
  }
  